name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - run: npm ci --no-production

      - run: npm run build
        env:
          NODE_ENV: production

      - name: Upload gh-pages
        uses: actions/upload-artifact@v2
        with:
          name: gh-pages
          path: build/**/*

  deploy-gh-pages:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: gh-pages
          path: gh-pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
